### ISSUE TITLE
Tasks for v3.2.0

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1038]
Tasks for the next minor upgrade version "v3.2.0". The following may be edited:

- [x] release note
- [x] release node server
- [x] `mount()`
- [x] Write documents
- [x] Check hostname based routing
- [x] export `fire()`
- [x] show router name?
- [x] Fix AWS Lambda bugs
- [x] Benchmark for measuring boot times.
- [x] #1033
- [x] Cookie Middleware
- [x] deprecate `c.cookie` and `c.req.cookie` #965 
- [x] `c.header('set-cookie', undefined)`
- [x] Create `hono/vercel` / deprecate `hono/nextjs`
- [x] ~~`app.bundleHandlers()` - experimental~~ #1072 
- [x] Create a starter template for Vercel
- [x] Remove HTTP status messages and remove status code Unions from `utils/http-status.ts`. #1037 
- [x] PatternRourter
- [x] LinearRouter
- [x] `hono/tiny`
- [x] `hono/quick` ?
- [x] Node Adapter supports Node.js native web standard API / as rc https://github.com/honojs/node-server/releases/tag/v1.0.0-rc.1
- [x] Allow routings with hostname #1064

## May not be implemeted

- [x] ~~deprecate `hono/adapter/*`~~
- [x] ~~PatternRouter as default ?~~
- [x] ~~HonoBase~~

**Comment by yusukebe** [comment]
Finished!
