### ISSUE TITLE
TODO for releasing v4

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#2149]
This is just like a note, it will be edited.

- [x] Merge https://github.com/honojs/node-server/pull/135 for Node.js Adapter
- [x] Update starter templates.
- [x] Merge `v4` branch to `main`. #2167
- [x] Merge v4 into main for the website. https://github.com/honojs/website/pull/235
- [x] Write a migration guide. #2159
- [x] Finish writing the v4 document for the website.
- [x] Write a release note.
- [x] Add new starter templates.
- [x] ~~Remove some experimental flags.~~ => later
