### ISSUE TITLE
Readmap to v1.2.0

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#216]
- [x] Handler and middlewares are treated as the same things #193 
- [x] `app.route(path, Route)` #203 
- [x] Multi match `trie-router` #196 
- [x] Multi match `reg-exp-router` #220 
- [x] Write document
