### ISSUE TITLE
Roadmap to v2.0.0

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#345]
Now, Hono has become a great framework. It has much built-in middleware, fine DX, flexible routings, and high-performance routers. Then, the basic API design is fixed. But I think we have a lot of things to do with Hono yet.

We can support Deno and Bun. It's still just experimental. We can make it complete.

How about making third-party middleware. The coupling of [firebase-auth-cloudflare-workers](https://github.com/Code-Hex/firebase-auth-cloudflare-workers) seems good. Organizing current middleware, I'm planning separate the middleware that does not depend on other libraries and middleware that depends on other libraries such as *graphql-server* or *mustache*. To make it clean, how about making the `github.com/honojs/graphql-server` repository, and moving current code into that. Additionally, how about using `@honojs/graphql-server` namespace in the npm repository. I've already got the `honojs` org in npm repo.

And, I want to make `validator` middleware. That is what I want.

In this way, we have many things to do. So, I decided to implement almost things and release them as **v2.0.0**. Is it good? Listed what I want to do roughly below. If you have a feature request. Please write it in the comments.

---

- [x] Support *Deno* #351 
- [x] Test well on *Deno* #351 
- [x] CI for Deno #364 
- [x] Support *Bun* #344 
- [x] `serve-static` middleware for Bun
- [x] Test on Bun
- [x] ~~Make repository for middleware using third party libraries~~ #350 
- [x] ~~Move the middleware using third party libs in current repository to new repository~~ later #350
- [x] ~~Use `honojs` org on npm repository~~ later #350
- [x] ~~Make `@honojs/xxx` namespace~~ later  #350 
- [x] ~~`github.com/honojs/xxx` repository~~ later #350 
- [x] ~~Make `validator` middleware as builtin~~ later
- [x] ~~`firebase-auth` middleware as third party~~ later
- [x] ~~`prometheus` middleware as third party~~ later #263 
- [x] Remove `graphql-server` middleware from this repo #357 
- [x] Remove `mustache` middleware from this repo #354 
- [x] ~~Access privileges for github repo~~ later
- [x] ~~Access privileges for npm repos~~ later
- [x] Make `body-parse` into `Context`? #362 
- [x] Make `cookie` into Request/Reponse #353 
- [x] ~~Integrate `app.fetch` and `app.request`?~~
- [x] New middleware structure #350 
- [x] Documenation
- [x] Website
- [x] Migration guide
- [x] And, others

By the way, we don't have to implement all things.

**Comment by Code-Hex** [comment]
Thanks for your great work!

I think this is a good example to manage way some middlewares to npm registry.

https://github.com/dotansimha/graphql-code-generator/tree/master/packages/plugins/typescript


This repository can manage some plugins in one repository. and each plugin has own dependencies as independent.

**Comment by metrue** [comment]
>And, I want to make validator middleware. That is what I want.
Are you talking about the graphql schema validation?

**Comment by yusukebe** [comment]
Hi @metrue !

> Are you talking about the graphql schema validation?

No, I want to validate Request *body* or *query parameters*.  For example, "express-validator" is similar to what I want to do.
<https://express-validator.github.io/docs/>

Like "express-validator", user can use [validator.js](https://github.com/validatorjs/validator.js). I think it's OK to use this library if user want to validate it perfectly. But, I want to have more tiny validator for casual use. It will be built-in middleware.

Although, I don't have plan for validation sytax, API design and, interface. We'll consider how we make it.

**Comment by yusukebe** [comment]
Hi @Code-Hex !

> I think this is an good example to manage way some middlewares to npm registry.

Thanks for sharing!

@Code-Hex  @metrue, I've written my thought about the middleware structure: #350 
Check it out.

**Comment by yusukebe** [comment]
I have another idea about a *validator* middleware.

Make the *validator* middleware as third-party middleware (**not built-in**) using [validator.js](https://github.com/validatorjs/validator.js). The repository will be `github.com/honojs/validator`, package name will be `@honojs/validator`.

It depends on the external library but, is easy to implement and it has many rules to validate. "validator.js" seems not to depend on other modules, so I think it works on Cloudflare Workers or Deno. We do not need polyfill.

**Comment by metrue** [comment]
Why this item  marked as completed? I did not find any repo github.com/honojs/graphql-server
- [x] Remove "graphql-server" middleware, it might be third-party middleware"

**Comment by yusukebe** [comment]
Hi @metrue 

I've removed "graphql-server" from this project, but I did not create the repository `github.com/honojs/graghql-server` yet.
After releasing v2.0.0 I'll create the repository for the middleware and implement it.

**Comment by metrue** [comment]
@yusukebe 
I see, I'm looking for what I help now.

**Comment by winston0410** [comment]
> Hi @metrue !
> 
> > Are you talking about the graphql schema validation?
> 
> No, I want to validate Request _body_ or _query parameters_. For example, "express-validator" is similar to what I want to do. https://express-validator.github.io/docs/
> 
> Like "express-validator", user can use [validator.js](https://github.com/validatorjs/validator.js). I think it's OK to use this library if user wants to validate it perfectly. But, I want to have more tiny validator for casual use. It will be built-in middleware.
> 
> Although, I don't have a plan for validation syntax, API design, and, interface. We'll consider how we make it.

I think I will help with that, it can be easily done with `ajv`, and I guess json schema is the answer for validating request body.
