### ISSUE TITLE
Roadmap to v2.2.0

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#514]
This is the roadmap to Hono v2.2.0.

One of the big changes is "migration CommonJS to ESM". It does not change API interfaces but may make it not work well on some environments. Wrangler, Deno, and Bun support importing ES Modules, so we don't have to worry that much, but we'll need to check.

There are a few other cool additions as well.

- [x] ~~Migrate CommonJS to ESM~~ Support ESM #502 #526 
- [x] Built-in Validator Middleware #505 #535
- [x] CORS middleware = Support multiple origins #503 
- [x] "Adaptor" server for Node.js `@honojs/node-server` - experimental / It may not be included in v2.2.0 #504 https://github.com/honojs/node-server
- [x] StaticRouter ? #501 
- [x] SmartRouter ? #501 
- [x] Lightweight RegExpRouter #519 
- [x] ~~Serve Static middleware for Node.js~~ #518  => later
- [x] #517 
- [x] #516 
- [x] Support multiple header values #536 
- [x] Support multiple cookie values #534 
- [x] Support optional parameter #540
- [x] Write the document for Validator middleware

When all features are implemented, we will ship as v2.2.0!

**Comment by yusukebe** [comment]
Almost done! I'll ship it soon!

**Comment by yusukebe** [comment]
Released now!

https://github.com/honojs/hono/releases/tag/v2.2.0
