### ISSUE TITLE
Validator: v.array() weird experience

### ISSUE THREAD

**Issue by Skye-31** [honojs/hono#677]
<details>

```js
import { Hono } from "hono";
import { validator } from "hono/validator";

const app = new Hono();

app.post(
	"/",
	validator(
		(v) => ({
			response: v.object("response", (v1) => ({
				content: v1.json("content").isOptional().isLength({ max: 2000 }),
				embeds: v1
					.array("embeds", (v2) => ({
						title: v2.json("title").isOptional(),
						description: v2.json("description").isOptional(),
						url: v2.json("url").isOptional(),
						timestamp: v2.json("timestamp").isOptional(),
						color: v2.json("color").asNumber().isOptional(),
						author: v2
							.object("embeds.[*].author", (v3) => ({
								name: v3.json("name").isOptional(),
								url: v3.json("url").isOptional(),
								icon_url: v3.json("icon_url").isOptional(),
							}))
							.isOptional(),
						footer: v2
							.object("embeds.[*].footer", (v3) => ({
								text: v3.json("text").isOptional(),
								icon_url: v3.json("icon_url").isOptional(),
							}))
							.isOptional(),
						image: v2
							.object("embeds.[*].image", (v3) => ({
								url: v3.json("url").isOptional(),
							}))
							.isOptional(),
						thumbnail: v2
							.object("embeds.[*].thumbnail", (v3) => ({
								url: v3.json("url").isOptional(),
							}))
							.isOptional(),
						fields: v2
							.array("embeds.[*].fields", (v3) => ({
								name: v3.json("name"),
								value: v3.json("value"),
								inline: v3.json("inline").isOptional().asBoolean(),
							}))
							.isOptional(),
					}))
					.isOptional(),
				flags: v1.json("flags").isOptional().asNumber(),
			})),
		}),
		{
			done: (res) => {
				if (res.hasError) {
					return new Response(res.messages.join("\n"), { status: 400 });
				}
			},
		}
	),
	(c) => {
		return Response.json(c.req.valid());
	}
);

app.notFound(() => {
	return new Response("Not found", { status: 404 });
})

export default app;
```
</details>

Issues:
- [x] 1. I have to use `fields: v2.array("embeds.[*].fields")` despite the fact it's already under `embeds` - if you don't it incorrectly looks under `response`. #683 
- [ ] 2. `v.array()` won't accept an empty array - even with it being marked as isOptional, the validator will error. This also occurs when `null` is provided. #690 
- [x] 3. `"Invalid Value [64]: the JSON body \"response.flags\" is invalid - should be \"number[]\""` - this is not under an array field - it should not be counted as an array? It turns out this can be fixed by putting `response.flags` before `response.embeds` in the validator - this is odd.  #680 

I appreciate this issue description is pretty awful - but I feel like I'm running into a combination of bugs here with nested arrays and objects

**Comment by Skye-31** [comment]
An example of some weird behaviour: 
![image](https://user-images.githubusercontent.com/46286597/203829971-b407c8e3-8a1c-42bf-a3e9-42fe292ec03b.png)

**Comment by yusukebe** [comment]
Hi @Skye-31 

Okay. I will investigate and fix it. It may take a little bit of time.

**Comment by dario-piotrowicz** [comment]
I had a little play with it and I've opened a PR for point 3 :slightly_smiling_face:

**Comment by dario-piotrowicz** [comment]
Hi @Skye-31 :slightly_smiling_face: , I am having a hard time understanding points 1 and 2, could you elaborate a bit? and could you maybe also please provide the requests you make and the expected vs actual response? :pray: 


Also you mention that for the fields you need to provide `'embeds.[*].fields'` but it should be just `'fields'` right? You specifically mention the fields, but doesn't the same apply for `author`, `footer`, `image` and `thumbnail` as well? is adding the prefix there ok?

**Comment by Skye-31** [comment]
Hi @dario-piotrowicz, of course. Thanks very much for looking at this!

The request body is here:
<details>

```json
{
    "response": {
    "content": "static response",
    "flags": 64,
    "embeds": [
      {
        "title": "Hi",
        "fields": [
          {
            "name": "field name",
            "value": "field value"
          }
        ]
      }
    ]
  }
}
```

</details>

For point 1, it appears that any deeper nested fields (for example an object, inside an array, inside an object), still require the prefix of the 2nd field to be included. In this case, if it was just `fields` (or author, footer, etc.), it incorrectly looks for `response.[*].fields`, when it should instead be looking under `response.embeds.[*].fields`. In all of these cases, I receive `Invalid Value [undefined]: the JSON body \"response.[*].<property> is invalid - should be <type>`. 

For point 2, if I provide `{ "response": { "content": "test", "embeds": [] } }`
I get the following: `Invalid Value [undefined]: the JSON body \"response.embeds.[*].title\" is invalid - should be \"string[]\"` - even though an empty array (as well as `undefined`) should be accepted as a value. 

Please let me know if I can clarify things any further

**Comment by dario-piotrowicz** [comment]
@Skye-31 thanks a bunch! :slightly_smiling_face:  I think I get it now :smiley::+1: I'll try to have a play around to see if I can spot the bugs :slightly_smiling_face: 

Regarding #680, I just tried the build locally and it doesn't seem to solve point 1 and 2 :sweat:

**Comment by yusukebe** [comment]
It seems that the point 2 is caused because it returns `false` if it's "array && optional && undefined".

**Comment by dario-piotrowicz** [comment]
@Skye-31 point 1 should be ok now :slightly_smiling_face::+1:

**Comment by Skye-31** [comment]
I've done some testing - and the experience seems *much* better than before so a big ❤️ for @dario-piotrowicz on this. There's still the issue of it rejecting empty embeds, but that's much more easy to get around than the other two

**Comment by dario-piotrowicz** [comment]
@Skye-31 Awesome! I'm so glad! :smiley: 

I'll look into the empty embeds issue soon :slightly_smiling_face::+1: 
(unless @yusukebe has already started and prefers to look into it? PS: @yusukebe I didn't fully understand your previous comment :sweat:)

**Comment by yusukebe** [comment]
@dario-piotrowicz 

I haven't worked on that yet!

Sorry for the lack of clarity. I suspect the problem is that it does not return `false` when `array && optional && undefined` in the `validateType`. I think.

https://github.com/honojs/hono/blob/07efdb5103c4cdb37585724945e26d93f33de383/src/validator/validator.ts#L304

**Comment by dario-piotrowicz** [comment]
> @dario-piotrowicz
> 
> I haven't worked on that yet!
> 
> Sorry for the lack of clarity. I suspect the problem is that it does not return "valid" when `this.isArray && this._optional && typeof value === 'undefined'` in the `validateType`. I think.
> 
> https://github.com/honojs/hono/blob/07efdb5103c4cdb37585724945e26d93f33de383/src/validator/validator.ts#L304

Ah ok I see, thanks for explaining, I'll have a look there then :smiley::+1: 

Anyways yeah if you haven't started on it I'll gladly try to fix the issue :slightly_smiling_face:

**Comment by dario-piotrowicz** [comment]
PR Opened :slightly_smiling_face:

**Comment by Skye-31** [comment]
Thanks again for taking a look at these @dario-piotrowicz! 

If it accepts undefined & empty arrays that's okay for me - While looking at the code for the validator earlier today I realised it doesn't accept null for optional objects, so it's consistent between the two.

**Comment by yusukebe** [comment]
Hi

> ok if you're good with null not being accepted then I guess we can do with that

Ah, `null`... I think this is a different issue whether it will be accepted or not, so let's go with this for this issue!
