### ISSUE TITLE
Roadmap for v3.0.0

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#736]
Let's go to the next step.

Now, Hono is used by many developers for several runtimes, such as Cloudflare Workers, Deno, or Bun. Many bugs have been fixed, and most features are working stably. On the other hand, "big" breaking changes, such as the introduction of HonoRequest, have become necessary. And we would like to add the "big" feature "RPC".

It is time to go to v3.0.0.

In addition, we will improve and rethink the Validator and refactor the internal code. Then, we have to write documents.

The [`next` branch](https://github.com/honojs/hono/tree/next) will be used for development towards v3.0.0.

Below are the TODOs for the v3.0.0 release. These lists are not complete and will be edited.

---

- [x] Migration guide
- [x] Update README
- [x] Middleware monorepo => Bump up Hono
- [x] ~~Update examples~~ Bump up Hono
- [x] ~~Update starter templates~~ Bump up Hono

## Done

- [x] Examples to use "RPC" [pages-stack](https://github.com/honojs/examples/tree/main/pages-stack)
- [x] Write documents!
- [x] Write a release note
- [x] ~~Write about uploading Files~~ Later
- [x] Rename `TypeResponse` to `TypedResponse`
- [x] ~~Validate param values~~
- [x] Return undefined instead of an empty string: query/queries/~~param~~
- [x] Implement Client for "PRC" #862 
- [x] ~~Add CI for edge-runtime(edge-light) ?~~
- [x] ~~Rename `hono/cloudflare-workers` to `hono/adapter/cloudflare-workers`?~~
- [x] Don't make "breaking changes" for `getPathFromURL` in utils.
- [x] ~~Don't include `Validator` in middleware?~~
- [x] tRPC Server Middleware
- [x] Use "vitepress" for `honojs.dev`, goodbye Hugo.
- [x] Add badge of "bundlephobia"
- [x] ~~`hc` support File Upload~~
- [x] `@honojs` to `@hono`
- [x] `@hono/graphql-server`
- [x] `@hono/sentry`
- [x] `@hono/firebase-auth`
- [x] Benchmark with complex routings #843 
- [x] ~~Migrate `yusukebe/pico` to `honojs/pico`~~
- [x] ~~Make compatibility with Hono and Pico~~
- [x] HonoRequest #733 #712 
- [x] "RPC" #727
- [x] Desing API of Client for "RPC"
- [x] ~~#614~~
- [x] ~~#710~~
- [x] ~~#623~~
- [x] ~~#725~~
- [x] ~~#726~~ 
- [x] ~~#724~~
- [x] Refactor for "Types"
- [x] ~~#702~~ 
- [x] Support "Zod" for a validation well
- [x] ~~Use another command instead of `wiptest` on Bun?~~
- [x] Lagon support #734 
- [x] Write tests for Lagon
- [x] Generally support Node.js with `@hono/node-server`
- [x] ~~"Hello World" examples on every runtimes?~~
- [x] Performance tuning
- [x] Flag to specify decode URL params or not
- [x] Improve headers matter in `Context` / finalize once?
- [x] Improve performance of methods in `HonoRequest`
- [x] Pre-release
- [x] Remove not used utils

**Comment by ClearedFram3** [comment]
Here are two frameworks that I think Hono might able to take inspiration from for 3.0
https://hyperstackjs.io/
https://deepkit.io/

**Comment by yusukebe** [comment]
@ClearedFram3 

I didn't know them. I'll check. Thank you!

**Comment by yusukebe** [comment]
Implementations of the features are almost done. I'm writing the documentation (will push it to the repo). It will ship soon.
