### ISSUE TITLE
Roadmap to v3.1.0

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#968]
Tasks for the next minor upgrade version "v3.1.0". The following may be edited.

- [x] `basePath` #964 
- [x] `env` #949 
- [x] Deprecate 2nd arg of `handle()` on Pages/Next.js adapter / Use instead `app.basePath()` to specify the base path. #981 
- [x] Consider handling Hono Client root endpoints #962 #971 #978
- [x] Consider the middleware behavior #960 #955 #970
- [x] Support inferring input/output of a validator #946 #969 
- [x] Update `@hono/zod-validator`
- [x] Update `@hono/typebox-validator`
- [x] ~~Client: `api.user["123"].get()`~~ => later
- [x] bun `wiptest` to `test` #977 977
- [x] AWS Lambda Adapter? #987 
- [x] `c.req.path` ?
- [x] Update starters

### May not be implemented

- [x] allow passing `RequestInit` to `c.json()` etc. #959 
- [x] ~~`hono()`~~

**Comment by yusukebe** [comment]
Done!
